### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by jackbrougher** [mhyhu/MEA-ToolBox#2]
Hello,

I was just wondering if you had any success running the MEA-ToolBox on Mac OS?

Cheers,

**Comment by mhyhu** [comment]
Hey Jack,

The executables on the github page and google drive were compiled in the windows environment.
We can't create an executable equivalent for the MAC OS because we don't have access to the licenses required for the MAC version of MATLAB and the compiler. However, we are trying to work on acquiring these licenses in the near future hopefully.
If you have MATLAB on your MAC OS then you can download the source code and run the software by starting the Main_Menu_Toolbox script.
Really sorry for the lack of support for the MAC OS.

Best,
Michel

**Comment by jackbrougher** [comment]
No worries! I was able to access a windows PC.

As a followup question, I installed the runtime and runtime version of the program on that system. However, now when I run the program I get the opening main page, but the only buttons on it are "parameters" and "help" - any suggestions or thoughts on what went wrong?

**Comment by mhyhu** [comment]
Hey Jack,

I can’t find your comment anymore on the GitHub page so I hope you will still receive this mail.
That is great news.
Yes, that was a deliberate choice we made.
In order to see the other buttons (analyse and load) you have to first set the parameters you want to use for the analysis.
If you want to use the default parameters you can press the parameters button which will make a new window appear and then you can press the save changes button to use the default parameters.
After this the other buttons will be available for you.
Please note that the test data in the google drive if they are hdf5 files then they still need to be analysed before they can be loaded.
If you have any other questions don’t hesitate to ask.

Best,
Michel

**Comment by jackbrougher** [comment]
Thanks for all the help! Last question, I promise.

When working with the Axion Biosciences system, do you suggest converting the files the an hdf5, or using the system's csv outputs. If the latter, which csv output, since the system has several options? If the former, do you have a suggested file conversion method?

**Comment by mhyhu** [comment]
Hey Jack,

No worries, please feel free to always ask questions.
Unfortunately, I haven't had the chance to work with the axion biosystems system myself.
However, we made the toolbox compatible with the csv format based on the 24 multiwell format with 16 electrodes in each well from axion biosystem.

We used a test data that was available from another toolbox (meaRtools).
Please take a look at their toolbox if you have R expertise as it is tailored to the output of axion biosystems.
(https://github.com/igm-team/meaRtools/tree/master/test/exampleRecording)
If you can export it like the csv file in the example recording listed above then you can run it like a hdf5 file in MEA-ToolBox.
However, please keep in mind that the MEA-Toolbox assumes that the csv files has **no** voltage trace data but only detected spikes. 

If you have a different well format please let me know then I can adjust the layout for you but you will have to provide me with a test output file so I know the organization of the electrodes. Then I can describe it similar to the 24 multiwell plate with 16 electrodes in the manual on page 5 and add it to MEA-ToolBox.
